import { Project } from './types';

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: "proj-1",
    title: "Smart Solar Powered Autonomous Dust Suppression System",
    domain: "IoT",
    branch: "Civil",
    type: "Product",
    price: 18500,
    description: "IoT-enabled misting system that monitors particulate matter (PM2.5/PM10) at construction sites and automatically deploys solar-powered dust suppression sprays.",
    imageUrl: "https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop",
    demoVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    tags: ["Solar", "Dust Suppression", "Air Quality", "Smart City"],
    featured: true,
  },
  {
    id: "proj-2",
    title: "AI-Driven EEG Brainwave Seizure Detection & Emergency Alert System",
    domain: "Machine Learning",
    branch: "Medical",
    type: "Prototype",
    price: 24500,
    description: "Deep neural network pipeline analyzing real-time wearable EEG signals to predict epileptic seizures 5 minutes before onset and alert caregivers via SMS.",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop",
    demoVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    tags: ["Healthcare", "Deep Learning", "Seizure Detection", "Wearable"],
    featured: true,
  },
  {
    id: "proj-3",
    title: "Autonomous Pipe Inspection Crawler Robot for Underground Utilities",
    domain: "Robotics",
    branch: "Mechanical",
    type: "Product",
    price: 31000,
    description: "Compact tracked robotic vehicle equipped with HD cameras, ultrasonic wall-thickness sensors, and obstacle avoidance for storm drain inspection.",
    imageUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop",
    demoVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    tags: ["Pipeline Robotics", "Inspection", "Tracked Rover", "Mechanical Design"],
    featured: true,
  },
  {
    id: "proj-4",
    title: "Edge-AI Microgrid Controller with Predictive Load Balancing",
    domain: "Large AI",
    branch: "EEE",
    type: "Product",
    price: 28999,
    description: "Embedded transformer AI model running on Jetson Nano that optimizes battery storage and solar inverter switching to prevent power grid overloads.",
    imageUrl: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&auto=format&fit=crop",
    demoVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    tags: ["Microgrid", "Energy Management", "Edge AI", "Power Systems"],
    featured: true,
  },
  {
    id: "proj-5",
    title: "FPGA-Accelerated Real-Time Chirp Radar Signal Processing Engine",
    domain: "Embedded",
    branch: "ECE",
    type: "Prototype",
    price: 14999,
    description: "High-frequency radar target detection architecture deployed on Xilinx Artix-7 FPGA with hardware FFT acceleration and low latency.",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop",
    demoVideoUrl: undefined,
    tags: ["FPGA", "Radar", "Signal Processing", "VHDL"],
    featured: false,
  },
  {
    id: "proj-6",
    title: "Distributed Blockchain Smart Contract System for Land Registry Verification",
    domain: "Machine Learning",
    branch: "CSE",
    type: "Prototype",
    price: 8999,
    description: "Immutable decentralised ledger combined with OCR document classification to eliminate fraudulent land title transfers in municipal administration.",
    imageUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop",
    demoVideoUrl: undefined,
    tags: ["Blockchain", "Land Registry", "Smart Contracts", "Security"],
    featured: false,
  },
  {
    id: "proj-7",
    title: "Computational Fluid Dynamics (CFD) Thermal Management Simulation for EV Battery Packs",
    domain: "Simulation",
    branch: "Mechanical",
    type: "Prototype",
    price: 12500,
    description: "ANSYS Fluent numerical simulation model optimizing coolant flow channels and phase-change material jackets for battery pack thermal runaway prevention.",
    imageUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop",
    demoVideoUrl: undefined,
    tags: ["CFD", "ANSYS", "EV Battery", "Thermal Management"],
    featured: true,
  },
  {
    id: "proj-8",
    title: "Smart Patient Bed Mobility & BedSore Prevention Assistive System",
    domain: "IoT",
    branch: "Medical",
    type: "Product",
    price: 19999,
    description: "Pressure-sensitive mattress array paired with pneumatic air actuators that automatically redistributes patient mass to prevent decubitus ulcers.",
    imageUrl: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop",
    demoVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    tags: ["Biomedical", "Assistive Tech", "Smart Hospital", "IoT"],
    featured: false,
  },
  {
    id: "proj-9",
    title: "Generative AI Assistant for Automated Structural CAD Blueprint Auditing",
    domain: "Large AI",
    branch: "Civil",
    type: "Prototype",
    price: 27500,
    description: "Multi-modal Large Vision-Language Model fine-tuned on IS 456 building codes to automatically detect missing shear rebar in engineering drawings.",
    imageUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop",
    demoVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    tags: ["LLM", "Structural CAD", "Building Codes", "GenAI"],
    featured: true,
  },
  {
    id: "proj-10",
    title: "Wireless Underwater Acoustic Modem for Marine Sensor Networks",
    domain: "Embedded",
    branch: "ECE",
    type: "Product",
    price: 16800,
    description: "Low-power acoustic transmitter unit using Orthogonal Frequency Division Multiplexing (OFDM) for reliable subsea telemetry up to 500 meters.",
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop",
    demoVideoUrl: undefined,
    tags: ["Underwater Telemetry", "OFDM", "Communication Systems", "Embedded"],
    featured: false,
  },
  {
    id: "proj-11",
    title: "Automated Sorting & Conveyor Arm using Machine Vision",
    domain: "Robotics",
    branch: "CSE",
    type: "Product",
    price: 22000,
    description: "4-DOF articulated robotic manipulator integrated with OpenCV object recognition to sort defective manufacturing components by color and dimension.",
    imageUrl: "https://images.unsplash.com/photo-1618042164219-62c820f10723?w=800&auto=format&fit=crop",
    demoVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    tags: ["Robotic Arm", "Machine Vision", "OpenCV", "Industrial Automation"],
    featured: true,
  },
  {
    id: "proj-12",
    title: "Grid-Tied Synchronous Inverter for Rooftop Solar PV Integration",
    domain: "Simulation",
    branch: "EEE",
    type: "Product",
    price: 15500,
    description: "MATLAB Simulink designed pure sine wave inverter with MPPT algorithm and reactive power compensation for stabilizing micro-grid voltages.",
    imageUrl: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&auto=format&fit=crop",
    demoVideoUrl: undefined,
    tags: ["Solar Inverter", "MPPT", "Power Electronics", "Simulink"],
    featured: false,
  },
  {
    id: "proj-13",
    title: "Non-Invasive Blood Glucose Monitor using Multi-Wavelength NIR Spectroscopy",
    domain: "Embedded",
    branch: "Medical",
    type: "Prototype",
    price: 11999,
    description: "Wearable wristband using near-infrared LED emission and photodiode signal amplification to estimate blood glucose levels without finger pricks.",
    imageUrl: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&auto=format&fit=crop",
    demoVideoUrl: undefined,
    tags: ["Biosensors", "Non-Invasive", "NIR Spectroscopy", "Health Tech"],
    featured: true,
  },
  {
    id: "proj-14",
    title: "Finite Element Stress & Vibration Simulation of Aircraft Jet Turbine Blades",
    domain: "Simulation",
    branch: "Mechanical",
    type: "Prototype",
    price: 9499,
    description: "Comprehensive FEA modal analysis in SolidWorks/ANSYS evaluating fatigue limits and thermal degradation of titanium alloy aero-engine blades under 12,000 RPM.",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop",
    demoVideoUrl: undefined,
    tags: ["FEA", "Aerospace", "Vibration Analysis", "ANSYS"],
    featured: false,
  },
  {
    id: "proj-15",
    title: "Smart Agricultural Soil Health & NPK Monitoring System",
    domain: "IoT",
    branch: "EEE",
    type: "Product",
    price: 6500,
    description: "Battery-operated LoRaWAN probe measuring soil pH, moisture, temperature, and nitrogen-phosphorus-potassium levels with cloud telemetry dashboard.",
    imageUrl: "https://images.unsplash.com/photo-1560493676-04071c5f467b?w=800&auto=format&fit=crop",
    demoVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    tags: ["Precision Farming", "LoRaWAN", "NPK Sensors", "IoT"],
    featured: false,
  },
  {
    id: "proj-16",
    title: "Computer Vision Traffic Density Analysis & Adaptive Signal Timing System",
    domain: "Machine Learning",
    branch: "Civil",
    type: "Product",
    price: 17200,
    description: "Real-time YOLOv8 vehicle counting system deployed at intersections to dynamically adjust green light duration according to traffic congestion queue length.",
    imageUrl: "https://images.unsplash.com/photo-1506521782020-18925f44e05b?w=800&auto=format&fit=crop",
    demoVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    tags: ["Traffic Management", "YOLOv8", "Smart City", "Computer Vision"],
    featured: true,
  },
  {
    id: "proj-17",
    title: "Self-Balancing Two-Wheeled Personal Mobility Transporter with Gesture Control",
    domain: "Robotics",
    branch: "ECE",
    type: "Prototype",
    price: 13999,
    description: "Microcontroller-based inverted pendulum system using 6-axis MPU6050 IMU sensors and PID control loops for gyro-stabilized personal transportation.",
    imageUrl: "https://images.unsplash.com/photo-1558442074-3c19857bc1dc?w=800&auto=format&fit=crop",
    demoVideoUrl: undefined,
    tags: ["PID Controller", "IMU", "Gyro Scope", "Robotics"],
    featured: false,
  },
  {
    id: "proj-18",
    title: "Autonomous Drone Swarm Coordination for Search & Rescue Operations",
    domain: "Large AI",
    branch: "CSE",
    type: "Prototype",
    price: 33500,
    description: "Decentralized multi-agent reinforcement learning algorithm permitting drone swarms to collaboratively map disaster terrain and locate missing survivors.",
    imageUrl: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop",
    demoVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    tags: ["Drone Swarm", "MARL", "Search & Rescue", "AI"],
    featured: true,
  },
  {
    id: "proj-19",
    title: "Automated ECG Cardiac Arrhythmia Classifier using 1D Convolutional Networks",
    domain: "Machine Learning",
    branch: "Medical",
    type: "Product",
    price: 7999,
    description: "Lightweight 1D-CNN trained on PhysioNet MIT-BIH database predicting atrial fibrillation and PVC premature contractions directly on mobile devices.",
    imageUrl: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=800&auto=format&fit=crop",
    demoVideoUrl: undefined,
    tags: ["Cardiology", "ECG", "1D-CNN", "Machine Learning"],
    featured: false,
  },
  {
    id: "proj-20",
    title: "IoT-Based Smart Water Quality & Contamination Early Warning System",
    domain: "IoT",
    branch: "ECE",
    type: "Product",
    price: 4999,
    description: "Multi-sensor node measuring turbidity, total dissolved solids (TDS), pH, and conductivity in municipal distribution pipes with immediate push notifications.",
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop",
    demoVideoUrl: undefined,
    tags: ["Water Quality", "Sensors", "Smart City", "IoT"],
    featured: false,
  }
];
